language: swift

osx_image: xcode12

addons:
  homebrew:
    packages:
      - swiftlint
    update: true

env:
  global:
    - PROJECT='Split.xcodeproj'
    - PLATFORM='iOS Simulator'
    - NAME='iPhone 11 Pro Max'
    - SCHEME='Split'
    - OS=13.2.2
    - LINTER_PKG_PATH="/tmp/SwiftLint.pkg"
    - LINTER_PKG_URL="https://github.com/realm/SwiftLint/releases/download/0.34.0/SwiftLint.pkg"

before_script:
  - DESTINATION="platform=${PLATFORM},OS=${OS},name=${NAME}"
  - BUILD_FOLDER='SplitApp'
  - mkdir "${BUILD_FOLDER}"

script:
  - swiftlint
  - set -o pipefail && xcodebuild -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -project "${PROJECT}" -scheme "${SCHEME}" -destination "${DESTINATION}" TEST_AFTER_BUILD=YES -derivedDataPath "${BUILD_FOLDER}" -configuration Debug build test | xcpretty