language: swift

osx_image: xcode10.2

env:
  linter:
    LINTER_PKG_PATH="/tmp/SwiftLint.pkg"
    LINTER_PKG_URL="https://github.com/realm/SwiftLint/releases/download/0.34.0/SwiftLint.pkg"
  global:
    - WORKSPACE='Split.xcodeproj'
    - PLATFORM='iOS Simulator'
    - NAME='iPhone 8'
    - SCHEME='Split'

install:
  - wget --output-document=$SWIFTLINT_PKG_PATH $SWIFTLINT_PKG_URL
  - if [ -f $SWIFTLINT_PKG_PATH ]; then sudo installer -pkg $SWIFTLINT_PKG_PATH -target

before_script:
  - DESTINATION="platform=${PLATFORM},OS=${OS},name=${NAME}"
  - BUILD_FOLDER='SplitApp'
  - mkdir "${BUILD_FOLDER}"

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace "${WORKSPACE}" -scheme "${SCHEME}" -destination "${DESTINATION}" -derivedDataPath "${BUILD_FOLDER}" build | xcpretty