name: Build and Test app

on:
  push:
    branches:
      - INFRA-3482
    pull_requests:
      - master
      - development

jobs:
  build:
    runs-on: [macos-latest]

    steps:
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 12.2

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        action: build test
        build-settings: ONLY_ACTIVE_ARCH=NO TEST_AFTER_BUILD=YES
        configuration: Debug
        derived-data-path: "${{github.workspace}}/SplitApp"
        destination: 'platform=iOS Simulator,OS=14.2,name=iPhone 11 Pro Max'
        project: Split.xcodeproj
        scheme: Split
        sdk: 'iphonesimulator'
        use-xcpretty: true
