name: Build xcframework

on:
  push:
    branches: 
      - test_xcframework

jobs:
  build:
    runs-on: [macos-latest]

    steps:
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 12.2

    - name: Checkout
      uses: actions/checkout@v2

    - name: Create xcframework for release
      run: ./gen_static_xcframework
      
    - name: Deploy S3 Development
      if: ${{ github.event_name == 'push' }}
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --cache-control max-age=31536000,public
      env:
        AWS_S3_BUCKET: 'aws-development-split-public'
        AWS_ACCESS_KEY_ID: ${{ secrets.PUBLIC_ASSETS_STAGE_USER }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PUBLIC_ASSETS_STAGE_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: './Split_XCFramework/Split.xcframework'
        DEST_DIR: sdk
